-- MySQL Workbench Synchronization

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP SCHEMA IF EXISTS `mydb` ;

ALTER TABLE `komvivo`.`catalog` 
ADD COLUMN `rowVersion` INT(11) NOT NULL AFTER `is_system_configuration`,
ADD COLUMN `eliminated` INT(11) NOT NULL AFTER `rowVersion`,
ADD COLUMN `user_creator` VARCHAR(45) NOT NULL AFTER `eliminated`,
ADD COLUMN `user_update` VARCHAR(45) NULL DEFAULT NULL AFTER `user_creator`,
ADD COLUMN `creation_date` DATETIME NOT NULL AFTER `user_update`,
ADD COLUMN `last_modify_date` DATETIME NULL DEFAULT NULL AFTER `creation_date`,
ADD COLUMN `guid` VARCHAR(40) NOT NULL AFTER `last_modify_date`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
